package Selenium;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class FeefoTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void example() throws IOException {
        driver.get("https://www.feefo.com/en-GB/reviews/mercedes-benz-south-west?displayFeedbackType=BOTH&timeFrame=YEAR");
        driver.manage().window().setSize(new Dimension(1050, 660));
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        List<WebElement> reviews = driver.findElements(By.xpath("//div['/html/body/div[1]/global/div/ui-view/ui-view/view-merchant/div/div/div/div/div/div/div[2]/div[1]/div']"));
        List<String> list = new ArrayList<>();
        for (WebElement webElement : reviews) {
            String review = webElement.getText();
            System.out.println(review);
            list.add(review);
        }
        FileWriter writer = new FileWriter("output6.txt");
        for(String str: list) {
            writer.write(str + System.lineSeparator() + System.lineSeparator() +System.lineSeparator());
        }
        writer.close();
    }
}
